export const FIND_REVIEWS_BY_PRODUCT_REQUEST =
  "FIND_REVIEWS_BY_PRODUCT_REQUEST";
export const FIND_REVIEWS_BY_PRODUCT_SUCCESS =
  "FIND_REVIEWS_BY_PRODUCT_SUCCESS";
export const FIND_REVIEWS_BY_PRODUCT_FAILURE =
  "FIND_REVIEWS_BY_PRODUCT_FAILURE";

export const FIND_RATINGS_BY_PRODUCT_REQUEST =
  "FIND_RATINGS_BY_PRODUCT_REQUEST";
export const FIND_RATINGS_BY_PRODUCT_SUCCESS =
  "FIND_RATINGS_BY_PRODUCT_SUCCESS";
export const FIND_RATINGS_BY_PRODUCT_FAILURE =
  "FIND_RATINGS_BY_PRODUCT_FAILURE";
