export const GET_CATEGORY_BY_LEVEL_REQUEST = "GET_CATEGORY_BY_LEVEL_REQUEST";
export const GET_CATEGORY_BY_LEVEL_SUCCESS = "GET_CATEGORY_BY_LEVEL_SUCCESS";
export const GET_CATEGORY_BY_LEVEL_FAILURE = "GET_CATEGORY_BY_LEVEL_FAILURE";
