export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST";
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS";
export const GET_ORDER_BY_ID_FAILURE = "GET_ORDER_BY_ID_FAILURE";

export const GET_ORDER_HISTORY_REQUEST = "GET_ORDER_HISTORY_REQUEST";
export const GET_ORDER_HISTORY_SUCCESS = "GET_ORDER_HISTORY_SUCCESS";
export const GET_ORDER_HISTORY_FAILURE = "GET_ORDER_HISTORY_FAILURE";

//admin
export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAILURE = "GET_ALL_ORDERS_FAILURE";

export const CONFIRM_ORDER_REQUEST = "CONFIRM_ORDER_REQUEST";
export const CONFIRM_ORDER_SUCCESS = "CONFIRM_ORDER_SUCCESS";
export const CONFIRM_ORDER_FAILURE = "CONFIRM_ORDER_FAILURE";

export const SHIPPED_ORDER_REQUEST = "SHIPPED_ORDER_REQUEST";
export const SHIPPED_ORDER_SUCCESS = "SHIPPED_ORDER_SUCCESS";
export const SHIPPED_ORDER_FAILURE = "SHIPPED_ORDER_FAILURE";

export const DELIVERED_ORDER_REQUEST = "DELIVERED_ORDER_REQUEST";
export const DELIVERED_ORDER_SUCCESS = "DELIVERED_ORDER_SUCCESS";
export const DELIVERED_ORDER_FAILURE = "DELIVERED_ORDER_FAILURE";

export const OUT_FOR_DELIVERY_ORDER_REQUEST = "OUT_FOR_DELIVERY_ORDER_REQUEST";
export const OUT_FOR_DELIVERY_ORDER_SUCCESS = "OUT_FOR_DELIVERY_ORDER_SUCCESS";
export const OUT_FOR_DELIVERY_ORDER_FAILURE = "OUT_FOR_DELIVERY_ORDER_FAILURE";

export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAILURE = "CANCEL_ORDER_FAILURE";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE";
